apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: cluster-config
spec:
  targetNamespace: istio-system
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: cluster-config
  interval: 1h0m0s
  install:
    remediation:
      retries: 3