apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  targetNamespace: istio-system
  releaseName: istiod
  chart:
    spec:
      chart: istio/istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      version: "1.22.3"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3